name: Code Embedder

on: pull_request

jobs:
  code_embedder:
    name: "Code embedder"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run code embedder
        uses: kvankova/code-embedder@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.CODE_EMBEDDER }}
